{
  imports = [
    ./spectre.nix
    ./flutter.nix
    ./octo.nix
    ./supermaven.nix
    ./tailwind.nix
    ./flash.nix
    ./spider.nix
    ./fzf.nix
    ./snack.nix
    ./lualine.nix
    ./plugins.nix
    ./mini.nix
    ./treesitter.nix
    ./tabout.nix
    ./navbuddy.nix
    ./neo-tree.nix
    ./neogit.nix
  ];
}
