
#[language-server.mylang-lsp]
#command = "mylang-lsp"

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "cpp"

[[language]]
name = "java"

[[language]]
name = "kotlin"

[[language]]
name = "svelte"

[[language]]
name = "gts"

[[language]]
name = "prisma"

[[language]]
name = "python"

[[language]]
name = "toml"

[[language]]
name = "nix"

[[language]]
name = "dockerfile"

[[language]]
name = "docker-compose"

[[language]]
name = "env"

[[language]]
name = "bash"

[[language]]
name = "html"

[[language]]
name = "css"

[[language]]
name = "lua"

[[language]]
name = "json"

[[language]]
name = "markdown"

[[language]]
name = "sql"

